name = "history-mrwuliu-top"
main = "./worker.js"
compatibility_date = "2024-01-01"
account_id = "6487ff5137937b16e91c02fb42372f75"

routes = [
  { pattern = "history.mrwuliu.top", custom_domain = true }
]

[site]
bucket = "./public"
