name: Deploy to Cloudflare Pages

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Deploy to Cloudflare Pages
        run: npx wrangler pages deploy public --project-name=history-mrwuliu-top --commit-dirty=true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: "6487ff5137937b16e91c02fb42372f75"
